[tool.poetry]
name = "NDPCC"
version = "1.0.0"
description = "Network design problem with chance constraints"
authors = ["Niels Wouda <n.a.wouda@rug.nl>"]

[tool.poetry.dependencies]
python = "^3.9"
gurobipy = "=9.1"
numpy = "^1.20"
pyyaml = "^5.4"
matplotlib = "^3.4"

# For generating experiments
pydoe2 = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
